<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE table top games [
<!ELEMENT table top game (game_name, character_name, commissioned_by, date, image_url)>
<!ELEMENT game_name (#PCDATA)>
<!ELEMENT character_name (#PCDATA)>
<!ELEMENT commissioned_by (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT image_url (#PCDATA)>
]

<table top game>
  <table_top_game>
    <game_name>Star Wars</game_name>
    <character_name>TBD</character_name>
    <commissioned_by>Fantasy Flight Games</commissioned_by>
    <date>2017</date>
    <image_url>TBD</image_url>
  </table_top_game>
